<?php

defined('MOODLE_INTERNAL') || die;

class local_documents_bulk_activity_completion_renderer extends plugin_renderer_base {


    public function __construct(moodle_page $page, $target)
    {
        parent::__construct($page, $target); // TODO: Change the autogenerated stub
    }

}